# SPARQL Query 3: Personas por altura/peso y número de clubes
# Endpoint: https://dbpedia.org/snorql/

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?person ?name (COUNT(?club) as ?numberOfClubs)
WHERE {
  ?person a dbo:Person .
  ?person rdfs:label ?name .
  OPTIONAL { ?person dbo:team ?club . }
  
  {
    { ?person dbo:height ?height . FILTER (?height >= 2.10) }
    UNION
    { ?person dbo:weight ?weight . FILTER (?weight >= 95000) }
  }
  
  FILTER (lang(?name) = 'en')
}
GROUP BY ?person ?name
ORDER BY ASC(?numberOfClubs)
LIMIT 7
